### PR TITLE
Add a cache-version parameter

### PR DESCRIPTION
**Pull request by ekohl**
This allows dealing with a corrupted cache. https://github.com/ruby/setup-ruby#dealing-with-a-corrupted-cache

### CODE REVIEW

**Comment by bastelfreak** [comment]
ah nice, I like the idea

**Comment by ekohl** [comment]
Ok, now I've pushed a working version :D

**Review by bastelfreak — APPROVED** [review]

**Comment by bastelfreak** [comment]
would that also make sense for the release job? we exclude our groups from the Gemfile, but still a cache is used?

**Comment by ekohl** [comment]
It kind of does, but in Foreman we didn't have the issue there so I skipped it for now. However, it would be consistent if we do.

**Pull request merged**
