### PR TITLE
GHA: Replace BEAKER_setfile->BEAKER_SETFILE env var

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
In Foreman we haven't updated voxpupuli-acceptance yet, so I fear this would break our pipelines.

**Comment by bastelfreak** [comment]
would this be a good point to create a V2 branch maybe?

**Comment by ekohl** [comment]
Maybe, but I'm hesitant. What's the value of doing this now? beaker-rspec hasn't stopped reading both. Having a longer transition window means we don't need to maintain two branches.

**Review by ekohl — CHANGES_REQUESTED** [review]
This, together with raising the Ruby version for acceptance tests to 3.2 and depending on https://github.com/voxpupuli/puppet_metadata/pull/35 would make a good v2 for gha-puppet. If you agree, I think we should create that branch and change the base branch on this PR.

**Comment by bastelfreak** [comment]
@ekohl yes that sounds awesome. Feel free to do it if you like, otherwise I can zake a look on monday or tuesday.

**Comment by bastelfreak** [comment]
@ekohl this now merges into the the new v2 branch.

**Review by ekohl — CHANGES_REQUESTED** [review]
I would like to merge https://github.com/voxpupuli/gha-puppet/pull/40 and then in this PR update the example to make `beaker-rspec` require `>= 8.0`, since that version introduced support for uppercase variables.

**Comment by bastelfreak** [comment]
@ekohl updated it.

**Review by ekohl — APPROVED** [review]

**Pull request merged**
